// this file is automatically generated, do not edit!
#ifndef ABANDONED_MINESHAFT_1_21_11_H
#define ABANDONED_MINESHAFT_1_21_11_H

#include "../loot_table_context.h"

LootTableContext* init_abandoned_mineshaft_1_21_11(int version);

#endif //ABANDONED_MINESHAFT_1_21_11_H
