// this file is automatically generated, do not edit!
#include "abandoned_mineshaft_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised_version = 0;

static char* item_names[21] = {"minecraft:golden_apple", "minecraft:enchanted_golden_apple", "minecraft:name_tag", "minecraft:book", "minecraft:iron_pickaxe", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:redstone", "minecraft:lapis_lazuli", "minecraft:diamond", "minecraft:coal", "minecraft:bread", "minecraft:glow_berries", "minecraft:melon_seeds", "minecraft:pumpkin_seeds", "minecraft:beetroot_seeds", "minecraft:rail", "minecraft:powered_rail", "minecraft:detector_rail", "minecraft:activator_rail", "minecraft:torch"};
static int global_item_ids[21] = {ITEM_GOLDEN_APPLE, ITEM_ENCHANTED_GOLDEN_APPLE, ITEM_NAME_TAG, ITEM_BOOK, ITEM_IRON_PICKAXE, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_REDSTONE, ITEM_LAPIS_LAZULI, ITEM_DIAMOND, ITEM_COAL, ITEM_BREAD, ITEM_GLOW_BERRIES, ITEM_MELON_SEEDS, ITEM_PUMPKIN_SEEDS, ITEM_BEETROOT_SEEDS, ITEM_RAIL, ITEM_POWERED_RAIL, ITEM_DETECTOR_RAIL, ITEM_ACTIVATOR_RAIL, ITEM_TORCH};

static int precomputed_loot__0[71] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5};
static int entry_to_item__0[6] = {0, 1, 2, 3, 4, -1};
static int entry_functions_count__0[6] = {0, 0, 0, 1, 0, 0};
static int entry_functions_index__0[6] = {0, 0, 0, 0, 1, 1};
static LootFunction loot_functions__0[1];
static const LootPool abandoned_mineshaft_1_21_11__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 6,
    .total_weight = 71,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[98] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10};
static int entry_to_item__1[11] = {5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static int entry_functions_count__1[11] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__1[11] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static LootFunction loot_functions__1[11];
static const LootPool abandoned_mineshaft_1_21_11__1 = {
    .min_rolls = 2,
    .max_rolls = 4,
    .roll_count_function = roll_count_uniform,
    .entry_count = 11,
    .total_weight = 98,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[50] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4};
static int entry_to_item__2[5] = {16, 17, 18, 19, 20};
static int entry_functions_count__2[5] = {1, 1, 1, 1, 1};
static int entry_functions_index__2[5] = {0, 1, 2, 3, 4};
static LootFunction loot_functions__2[5];
static const LootPool abandoned_mineshaft_1_21_11__2 = {
    .min_rolls = 3,
    .max_rolls = 3,
    .roll_count_function = roll_count_constant,
    .entry_count = 5,
    .total_weight = 50,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};

static LootPool loot_pools[3] = {abandoned_mineshaft_1_21_11__0, abandoned_mineshaft_1_21_11__1, abandoned_mineshaft_1_21_11__2};
static LootTableContext context = {
    .version = 0, // set by init
    .item_count = 21,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 3,
    .loot_pools = loot_pools,
};

    static void create_loot_functions(int version) {
(void)version; // unused when the table has no enchantment functions
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_enchant_randomly_tag(&(loot_pool__0->loot_functions[0]), version, get_item_type("minecraft:book"), "#minecraft:on_random_loot", 0);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 5);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 3);
    create_set_count(&(loot_pool__1->loot_functions[2]), 4, 9);
    create_set_count(&(loot_pool__1->loot_functions[3]), 4, 9);
    create_set_count(&(loot_pool__1->loot_functions[4]), 1, 2);
    create_set_count(&(loot_pool__1->loot_functions[5]), 3, 8);
    create_set_count(&(loot_pool__1->loot_functions[6]), 1, 3);
    create_set_count(&(loot_pool__1->loot_functions[7]), 3, 6);
    create_set_count(&(loot_pool__1->loot_functions[8]), 2, 4);
    create_set_count(&(loot_pool__1->loot_functions[9]), 2, 4);
    create_set_count(&(loot_pool__1->loot_functions[10]), 2, 4);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 4, 8);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 4);
    create_set_count(&(loot_pool__2->loot_functions[2]), 1, 4);
    create_set_count(&(loot_pool__2->loot_functions[3]), 1, 4);
    create_set_count(&(loot_pool__2->loot_functions[4]), 1, 16);
}

LootTableContext* init_abandoned_mineshaft_1_21_11(int version) {
    // Rebuild if the requested version differs: enchantment registries are
    // version dependent, and one table file serves a range of versions.
    if (initialised_version != version) {
        context.version = version;
        create_loot_functions(version);
        initialised_version = version;
    }
    return &context;
}
