// this file is automatically generated, do not edit!
#include "ancient_city_ice_box_26_2.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised_version = 0;

static char* item_names[5] = {"minecraft:suspicious_stew", "minecraft:golden_carrot", "minecraft:baked_potato", "minecraft:packed_ice", "minecraft:snowball"};
static int global_item_ids[5] = {ITEM_SUSPICIOUS_STEW, ITEM_GOLDEN_CARROT, ITEM_BAKED_POTATO, ITEM_PACKED_ICE, ITEM_SNOWBALL};

static int precomputed_loot__0[9] = {0, 1, 2, 3, 3, 4, 4, 4, 4};
static int entry_to_item__0[5] = {0, 1, 2, 3, 4};
static int entry_functions_count__0[5] = {2, 1, 1, 1, 1};
static int entry_functions_index__0[5] = {0, 2, 3, 4, 5};
static LootFunction loot_functions__0[6];
static const LootPool ancient_city_ice_box_26_2__0 = {
    .min_rolls = 4,
    .max_rolls = 10,
    .roll_count_function = roll_count_uniform,
    .entry_count = 5,
    .total_weight = 9,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {ancient_city_ice_box_26_2__0};
static LootTableContext context = {
    .version = 0, // set by init
    .item_count = 5,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

    static void create_loot_functions(int version) {
(void)version; // unused when the table has no enchantment functions
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_effect(&(loot_pool__0->loot_functions[0]), 2, (MobEffectEntry[]){{get_mob_effect_from_name("minecraft:night_vision"), 7, 10}, {get_mob_effect_from_name("minecraft:blindness"), 5, 7}});
    create_set_count(&(loot_pool__0->loot_functions[1]), 2, 6);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 10);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 10);
    create_set_count(&(loot_pool__0->loot_functions[4]), 2, 6);
    create_set_count(&(loot_pool__0->loot_functions[5]), 2, 6);
}

LootTableContext* init_ancient_city_ice_box_26_2(int version) {
    // Rebuild if the requested version differs: enchantment registries are
    // version dependent, and one table file serves a range of versions.
    if (initialised_version != version) {
        context.version = version;
        create_loot_functions(version);
        initialised_version = version;
    }
    return &context;
}
