// this file is automatically generated, do not edit!
#ifndef ANCIENT_CITY_1_20_H
#define ANCIENT_CITY_1_20_H

#include "../loot_table_context.h"

LootTableContext* init_ancient_city_1_20(int version);

#endif //ANCIENT_CITY_1_20_H
