// this file is automatically generated, do not edit!
#ifndef ANCIENT_CITY_26_2_H
#define ANCIENT_CITY_26_2_H

#include "../loot_table_context.h"

LootTableContext* init_ancient_city_26_2(int version);

#endif //ANCIENT_CITY_26_2_H
