// this file is automatically generated, do not edit!
#ifndef ANCIENT_CITY_1_21_11_H
#define ANCIENT_CITY_1_21_11_H

#include "../loot_table_context.h"

LootTableContext* init_ancient_city_1_21_11(int version);

#endif //ANCIENT_CITY_1_21_11_H
