// this file is automatically generated, do not edit!
#ifndef ANCIENT_CITY_26_1_H
#define ANCIENT_CITY_26_1_H

#include "../loot_table_context.h"

LootTableContext* init_ancient_city_26_1(int version);

#endif //ANCIENT_CITY_26_1_H
