// this file is automatically generated, do not edit!
#include "ancient_city_1_21_1.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised_version = 0;

static char* item_names[30] = {"minecraft:enchanted_golden_apple", "minecraft:music_disc_otherside", "minecraft:compass", "minecraft:sculk_catalyst", "minecraft:name_tag", "minecraft:diamond_hoe", "minecraft:lead", "minecraft:diamond_horse_armor", "minecraft:saddle", "minecraft:music_disc_13", "minecraft:music_disc_cat", "minecraft:diamond_leggings", "minecraft:book", "minecraft:sculk", "minecraft:sculk_sensor", "minecraft:candle", "minecraft:amethyst_shard", "minecraft:experience_bottle", "minecraft:glow_berries", "minecraft:iron_leggings", "minecraft:echo_shard", "minecraft:disc_fragment_5", "minecraft:potion", "minecraft:book", "minecraft:book", "minecraft:bone", "minecraft:soul_torch", "minecraft:coal", "minecraft:ward_armor_trim_smithing_template", "minecraft:silence_armor_trim_smithing_template"};
static int global_item_ids[30] = {ITEM_ENCHANTED_GOLDEN_APPLE, ITEM_MUSIC_DISC_OTHERSIDE, ITEM_COMPASS, ITEM_SCULK_CATALYST, ITEM_NAME_TAG, ITEM_DIAMOND_HOE, ITEM_LEAD, ITEM_DIAMOND_HORSE_ARMOR, ITEM_SADDLE, ITEM_MUSIC_DISC_13, ITEM_MUSIC_DISC_CAT, ITEM_DIAMOND_LEGGINGS, ITEM_BOOK, ITEM_SCULK, ITEM_SCULK_SENSOR, ITEM_CANDLE, ITEM_AMETHYST_SHARD, ITEM_EXPERIENCE_BOTTLE, ITEM_GLOW_BERRIES, ITEM_IRON_LEGGINGS, ITEM_ECHO_SHARD, ITEM_DISC_FRAGMENT_5, ITEM_POTION, ITEM_BOOK, ITEM_BOOK, ITEM_BONE, ITEM_SOUL_TORCH, ITEM_COAL, ITEM_WARD_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE};

static int precomputed_loot__0[86] = {0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27};
static int entry_to_item__0[28] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 12, 12, 25, 26, 27};
static int entry_functions_count__0[28] = {1, 0, 1, 1, 0, 3, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1};
static int entry_functions_index__0[28] = {0, 1, 1, 2, 3, 3, 6, 7, 8, 9, 9, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26};
static LootFunction loot_functions__0[27];
static const LootPool ancient_city_1_21_1__0 = {
    .min_rolls = 5,
    .max_rolls = 10,
    .roll_count_function = roll_count_uniform,
    .entry_count = 28,
    .total_weight = 86,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[80] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2};
static int entry_to_item__1[3] = {-1, 28, 29};
static int entry_functions_count__1[3] = {0, 0, 0};
static int entry_functions_index__1[3] = {0, 0, 0};
static LootFunction loot_functions__1[0];
static const LootPool ancient_city_1_21_1__1 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 3,
    .total_weight = 80,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {ancient_city_1_21_1__0, ancient_city_1_21_1__1};
static LootTableContext context = {
    .version = 0, // set by init
    .item_count = 30,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

    static void create_loot_functions(int version) {
(void)version; // unused when the table has no enchantment functions
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 2);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 2);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 1);
    create_skip_calls(&(loot_pool__0->loot_functions[4]), 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[5]), version, "minecraft:diamond_hoe", get_item_type("minecraft:diamond_hoe"), 30, 50, "#minecraft:on_random_loot", 1);
    create_set_count(&(loot_pool__0->loot_functions[6]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[7]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[8]), 1, 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[9]), version, "minecraft:diamond_leggings", get_item_type("minecraft:diamond_leggings"), 30, 50, "#minecraft:on_random_loot", 1);
    create_enchant_randomly_one_enchant(&(loot_pool__0->loot_functions[10]), get_enchantment_from_name("minecraft:swift_sneak"));
    create_set_count(&(loot_pool__0->loot_functions[11]), 4, 10);
    create_set_count(&(loot_pool__0->loot_functions[12]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[13]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[14]), 1, 15);
    create_set_count(&(loot_pool__0->loot_functions[15]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[16]), 1, 15);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[17]), version, "minecraft:iron_leggings", get_item_type("minecraft:iron_leggings"), 20, 39, "#minecraft:on_random_loot", 1);
    create_set_count(&(loot_pool__0->loot_functions[18]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[19]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[20]), 1, 3);
    create_set_potion(&(loot_pool__0->loot_functions[21]), get_potion_from_name("minecraft:strong_regeneration"));
    create_enchant_randomly_tag(&(loot_pool__0->loot_functions[22]), version, get_item_type("minecraft:book"), "#minecraft:on_random_loot", 0);
    create_set_count(&(loot_pool__0->loot_functions[23]), 3, 10);
    create_set_count(&(loot_pool__0->loot_functions[24]), 1, 15);
    create_set_count(&(loot_pool__0->loot_functions[25]), 1, 15);
    create_set_count(&(loot_pool__0->loot_functions[26]), 6, 15);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
}

LootTableContext* init_ancient_city_1_21_1(int version) {
    // Rebuild if the requested version differs: enchantment registries are
    // version dependent, and one table file serves a range of versions.
    if (initialised_version != version) {
        context.version = version;
        create_loot_functions(version);
        initialised_version = version;
    }
    return &context;
}
